export const vehicleClasses = ['Gr. 1', 'Gr. 2', 'Gr. 3', 'Gr. 4', 'Gr. B', 'SPEC', 'Other'];
export const contactOptions = ['Discord', 'Email'];

export const apiConnectorDictionary = {
  UsStates: [
    'Alabama',
    'Alaska',
    'America Samoa',
    'Arizona',
    'Arkansas',
    'California',
    'Colorado',
    'Connecticut',
    'Delaware',
    'Florida',
    'Georgia',
    'Guam',
    'Hawaii',
    'Idaho',
    'Illinois',
    'Indiana',
    'Iowa',
    'Kansas',
    'Kentucky',
    'Louisiana',
    'Maine',
    'Maryland',
    'Massachusetts',
    'Michigan',
    'Minnesota',
    'Mississippi',
    'Missouri',
    'Montana',
    'Nebraska',
    'Nevada',
    'New Hampshire',
    'New Jersey',
    'New Mexico',
    'New York',
    'North Carolina',
    'North Dakota',
    'Ohio',
    'Oklahoma',
    'Oregon',
    'Palau',
    'Pennsylvania',
    'Puerto Rico',
    'Rhode Island',
    'South Carolina',
    'South Dakota',
    'Tennessee',
    'Texas',
    'Utah',
    'Vermont',
    'Virgin Island',
    'Virginia',
    'Washington',
    'Washington D.C.',
    'West Virginia',
    'Wisconsin',
    'Wyoming',
  ],
  Countries: ['United States', 'Canada', 'Mexico'],
  provinces: [
    'Ontario',
    'Quebec',
    'Nova Scotia',
    'New Brunswick',
    'Manitoba',
    'British Columbia',
    'Prince Edward Island',
    'Saskatchewan',
    'Alberta',
    'Newfoundland & Labrador',
    'Northwest Territories',
    'Yukon',
    'Nunavut',
  ],
  mexicanStates: [
    'Aguascalientes',
    'Baja California',
    'Baja California Sur',
    'Campeche',
    'Chiapas',
    'Chihuahua',
    'Coahuila',
    'Colima',
    'Mexico City',
    'Durango',
    'Guanajuato',
    'Guerrero',
    'Hidalgo',
    'Jalisco',
    'México',
    'Michoacán',
    'Morelos',
    'Nayarit',
    'Nuevo León',
    'Oaxaca',
    'Puebla',
    'Querétaro',
    'Quintana Roo',
    'San Luis Potosí',
    'Sinaloa',
    'Sonora',
    'Tabasco',
    'Tamaulipas',
    'Tlaxcala',
    'Veracruz',
    'Yucatán',
    'Zacatecas',
  ],
};

export const numberMonths: string[] = [
  '01',
  '02',
  '03',
  '04',
  '05',
  '06',
  '07',
  '08',
  '09',
  '10',
  '11',
  '12',
];

export const usStateAndAbbreviation: { name: string; abbreviation: string }[] = [
  { name: 'ALABAMA', abbreviation: 'AL' },
  { name: 'ALASKA', abbreviation: 'AK' },
  { name: 'AMERICAN SAMOA', abbreviation: 'AS' },
  { name: 'ARIZONA', abbreviation: 'AZ' },
  { name: 'ARKANSAS', abbreviation: 'AR' },
  { name: 'CALIFORNIA', abbreviation: 'CA' },
  { name: 'COLORADO', abbreviation: 'CO' },
  { name: 'Connecticut', abbreviation: 'CT' },
  { name: 'DELAWARE', abbreviation: 'DE' },
  { name: 'DISTRICT OF COLUMBIA', abbreviation: 'DC' },
  { name: 'Washington D.C.', abbreviation: 'DC' },
  { name: 'FEDERATED STATES OF MICRONESIA', abbreviation: 'FM' },
  { name: 'FLORIDA', abbreviation: 'FL' },
  { name: 'GEORGIA', abbreviation: 'GA' },
  { name: 'GUAM', abbreviation: 'GU' },
  { name: 'HAWAII', abbreviation: 'HI' },
  { name: 'IDAHO', abbreviation: 'ID' },
  { name: 'ILLINOIS', abbreviation: 'IL' },
  { name: 'INDIANA', abbreviation: 'IN' },
  { name: 'IOWA', abbreviation: 'IA' },
  { name: 'KANSAS', abbreviation: 'KS' },
  { name: 'KENTUCKY', abbreviation: 'KY' },
  { name: 'LOUISIANA', abbreviation: 'LA' },
  { name: 'MAINE', abbreviation: 'ME' },
  { name: 'MARSHALL ISLANDS', abbreviation: 'MH' },
  { name: 'MARYLAND', abbreviation: 'MD' },
  { name: 'MASSACHUSETTS', abbreviation: 'MA' },
  { name: 'MICHIGAN', abbreviation: 'MI' },
  { name: 'MINNESOTA', abbreviation: 'MN' },
  { name: 'MISSISSIPPI', abbreviation: 'MS' },
  { name: 'MISSOURI', abbreviation: 'MO' },
  { name: 'MONTANA', abbreviation: 'MT' },
  { name: 'NEBRASKA', abbreviation: 'NE' },
  { name: 'NEVADA', abbreviation: 'NV' },
  { name: 'NEW HAMPSHIRE', abbreviation: 'NH' },
  { name: 'NEW JERSEY', abbreviation: 'NJ' },
  { name: 'NEW MEXICO', abbreviation: 'NM' },
  { name: 'NEW YORK', abbreviation: 'NY' },
  { name: 'NORTH CAROLINA', abbreviation: 'NC' },
  { name: 'NORTH DAKOTA', abbreviation: 'ND' },
  { name: 'NORTHERN MARIANA ISLANDS', abbreviation: 'MP' },
  { name: 'OHIO', abbreviation: 'OH' },
  { name: 'OKLAHOMA', abbreviation: 'OK' },
  { name: 'OREGON', abbreviation: 'OR' },
  { name: 'PALAU', abbreviation: 'PW' },
  { name: 'PENNSYLVANIA', abbreviation: 'PA' },
  { name: 'PUERTO RICO', abbreviation: 'PR' },
  { name: 'RHODE ISLAND', abbreviation: 'RI' },
  { name: 'SOUTH CAROLINA', abbreviation: 'SC' },
  { name: 'SOUTH DAKOTA', abbreviation: 'SD' },
  { name: 'TENNESSEE', abbreviation: 'TN' },
  { name: 'TEXAS', abbreviation: 'TX' },
  { name: 'UTAH', abbreviation: 'UT' },
  { name: 'VERMONT', abbreviation: 'VT' },
  { name: 'VIRGIN ISLANDS', abbreviation: 'VI' },
  { name: 'VIRGINIA', abbreviation: 'VA' },
  { name: 'WASHINGTON', abbreviation: 'WA' },
  { name: 'WEST VIRGINIA', abbreviation: 'WV' },
  { name: 'WISCONSIN', abbreviation: 'WI' },
  { name: 'WYOMING', abbreviation: 'WY' },
];

export const canadianProvincesAndAbbreviations: { name: string; abbreviation: string }[] = [
  { name: 'Ontario', abbreviation: 'ON' },
  { name: 'Quebec', abbreviation: 'QC' },
  { name: 'Nova Scotia', abbreviation: 'NS' },
  { name: 'New Brunswick', abbreviation: 'NB' },
  { name: 'Manitoba', abbreviation: 'MB' },
  { name: 'British Columbia', abbreviation: 'BC' },
  { name: 'Prince Edward Island', abbreviation: 'PE' },
  { name: 'Saskatchewan', abbreviation: 'SK' },
  { name: 'Alberta', abbreviation: 'AB' },
  { name: 'Newfoundland & Labrador', abbreviation: 'NL' },
  { name: 'Northwest Territories', abbreviation: 'NT' },
  { name: 'Yukon', abbreviation: 'YT' },
  { name: 'Nunavut', abbreviation: 'NU' },
];

export const mexcianStatesAndAbbreviations = [
  { name: 'Aguascalientes', abbreviation: 'Ags.' },
  { name: 'Baja California', abbreviation: 'B.C.' },
  {
    name: 'Baja California Sur',
    abbreviation: 'B.C.S.',
  },
  { name: 'Campeche', abbreviation: 'Camp.' },
  { name: 'Chiapas', abbreviation: 'Chis.' },
  { name: 'Chihuahua', abbreviation: 'Chih.' },
  { name: 'Coahuila', abbreviation: 'Coah.' },
  { name: 'Colima', abbreviation: 'Col.' },
  { name: 'Mexico City', abbreviation: 'CDMX' },
  { name: 'Durango', abbreviation: 'Dgo.' },
  { name: 'Guanajuato', abbreviation: 'Gto.' },
  { name: 'Guerrero', abbreviation: 'Gro.' },
  { name: 'Hidalgo', abbreviation: 'Hgo.' },
  { name: 'Jalisco', abbreviation: 'Jal.' },
  { name: 'México', abbreviation: 'Méx.' },
  { name: 'Michoacán', abbreviation: 'Mich.' },
  { name: 'Morelos', abbreviation: 'Mor.' },
  { name: 'Nayarit', abbreviation: 'Nay.' },
  { name: 'Nuevo León', abbreviation: 'N.L.' },
  { name: 'Oaxaca', abbreviation: 'Oax.' },
  { name: 'Puebla', abbreviation: 'Pue.' },
  { name: 'Querétaro', abbreviation: 'Qro.' },
  {
    name: 'Quintana Roo',
    abbreviation: 'Q. Roo.',
  },
  { name: 'San Luis Potosí', abbreviation: ['S.L.P.'], iso2: 'SL', iso3: 'SLP', internal: 'SLP' },
  { name: 'Sinaloa', abbreviation: 'Sin.' },
  { name: 'Sonora', abbreviation: 'Son.' },
  { name: 'Tabasco', abbreviation: 'Tab.' },
  { name: 'Tamaulipas', abbreviation: 'Tamps.' },
  { name: 'Tlaxcala', abbreviation: 'Tlax.' },
  { name: 'Veracruz', abbreviation: 'Ver.' },
  { name: 'Yucatán', abbreviation: 'Yuc.' },
  { name: 'Zacatecas', abbreviation: 'Zac.' },
];
export const allCountries = [
  { name: 'Afghanistan', code: 'AF' },
  { name: 'Åland Islands', code: 'AX' },
  { name: 'Albania', code: 'AL' },
  { name: 'Algeria', code: 'DZ' },
  { name: 'American Samoa', code: 'AS' },
  { name: 'AndorrA', code: 'AD' },
  { name: 'Angola', code: 'AO' },
  { name: 'Anguilla', code: 'AI' },
  { name: 'Antarctica', code: 'AQ' },
  { name: 'Antigua and Barbuda', code: 'AG' },
  { name: 'Argentina', code: 'AR' },
  { name: 'Armenia', code: 'AM' },
  { name: 'Aruba', code: 'AW' },
  { name: 'Australia', code: 'AU' },
  { name: 'Austria', code: 'AT' },
  { name: 'Azerbaijan', code: 'AZ' },
  { name: 'Bahamas', code: 'BS' },
  { name: 'Bahrain', code: 'BH' },
  { name: 'Bangladesh', code: 'BD' },
  { name: 'Barbados', code: 'BB' },
  { name: 'Belarus', code: 'BY' },
  { name: 'Belgium', code: 'BE' },
  { name: 'Belize', code: 'BZ' },
  { name: 'Benin', code: 'BJ' },
  { name: 'Bermuda', code: 'BM' },
  { name: 'Bhutan', code: 'BT' },
  { name: 'Bolivia', code: 'BO' },
  { name: 'Bosnia and Herzegovina', code: 'BA' },
  { name: 'Botswana', code: 'BW' },
  { name: 'Bouvet Island', code: 'BV' },
  { name: 'Brazil', code: 'BR' },
  { name: 'British Indian Ocean Territory', code: 'IO' },
  { name: 'Brunei Darussalam', code: 'BN' },
  { name: 'Bulgaria', code: 'BG' },
  { name: 'Burkina Faso', code: 'BF' },
  { name: 'Burundi', code: 'BI' },
  { name: 'Cambodia', code: 'KH' },
  { name: 'Cameroon', code: 'CM' },
  { name: 'Canada', code: 'CA' },
  { name: 'Cape Verde', code: 'CV' },
  { name: 'Cayman Islands', code: 'KY' },
  { name: 'Central African Republic', code: 'CF' },
  { name: 'Chad', code: 'TD' },
  { name: 'Chile', code: 'CL' },
  { name: 'China', code: 'CN' },
  { name: 'Christmas Island', code: 'CX' },
  { name: 'Cocos (Keeling) Islands', code: 'CC' },
  { name: 'Colombia', code: 'CO' },
  { name: 'Comoros', code: 'KM' },
  { name: 'Congo', code: 'CG' },
  { name: 'Congo, The Democratic Republic of the', code: 'CD' },
  { name: 'Cook Islands', code: 'CK' },
  { name: 'Costa Rica', code: 'CR' },
  { name: "Cote D'Ivoire", code: 'CI' },
  { name: 'Croatia', code: 'HR' },
  { name: 'Cuba', code: 'CU' },
  { name: 'Cyprus', code: 'CY' },
  { name: 'Czech Republic', code: 'CZ' },
  { name: 'Denmark', code: 'DK' },
  { name: 'Djibouti', code: 'DJ' },
  { name: 'Dominica', code: 'DM' },
  { name: 'Dominican Republic', code: 'DO' },
  { name: 'Ecuador', code: 'EC' },
  { name: 'Egypt', code: 'EG' },
  { name: 'El Salvador', code: 'SV' },
  { name: 'Equatorial Guinea', code: 'GQ' },
  { name: 'Eritrea', code: 'ER' },
  { name: 'Estonia', code: 'EE' },
  { name: 'Ethiopia', code: 'ET' },
  { name: 'Falkland Islands (Malvinas)', code: 'FK' },
  { name: 'Faroe Islands', code: 'FO' },
  { name: 'Fiji', code: 'FJ' },
  { name: 'Finland', code: 'FI' },
  { name: 'France', code: 'FR' },
  { name: 'French Guiana', code: 'GF' },
  { name: 'French Polynesia', code: 'PF' },
  { name: 'French Southern Territories', code: 'TF' },
  { name: 'Gabon', code: 'GA' },
  { name: 'Gambia', code: 'GM' },
  { name: 'Georgia', code: 'GE' },
  { name: 'Germany', code: 'DE' },
  { name: 'Ghana', code: 'GH' },
  { name: 'Gibraltar', code: 'GI' },
  { name: 'Greece', code: 'GR' },
  { name: 'Greenland', code: 'GL' },
  { name: 'Grenada', code: 'GD' },
  { name: 'Guadeloupe', code: 'GP' },
  { name: 'Guam', code: 'GU' },
  { name: 'Guatemala', code: 'GT' },
  { name: 'Guernsey', code: 'GG' },
  { name: 'Guinea', code: 'GN' },
  { name: 'Guinea-Bissau', code: 'GW' },
  { name: 'Guyana', code: 'GY' },
  { name: 'Haiti', code: 'HT' },
  { name: 'Heard Island and Mcdonald Islands', code: 'HM' },
  { name: 'Holy See (Vatican City State)', code: 'VA' },
  { name: 'Honduras', code: 'HN' },
  { name: 'Hong Kong', code: 'HK' },
  { name: 'Hungary', code: 'HU' },
  { name: 'Iceland', code: 'IS' },
  { name: 'India', code: 'IN' },
  { name: 'Indonesia', code: 'ID' },
  { name: 'Iran, Islamic Republic Of', code: 'IR' },
  { name: 'Iraq', code: 'IQ' },
  { name: 'Ireland', code: 'IE' },
  { name: 'Isle of Man', code: 'IM' },
  { name: 'Israel', code: 'IL' },
  { name: 'Italy', code: 'IT' },
  { name: 'Jamaica', code: 'JM' },
  { name: 'Japan', code: 'JP' },
  { name: 'Jersey', code: 'JE' },
  { name: 'Jordan', code: 'JO' },
  { name: 'Kazakhstan', code: 'KZ' },
  { name: 'Kenya', code: 'KE' },
  { name: 'Kiribati', code: 'KI' },
  { name: "Korea, Democratic People'S Republic of", code: 'KP' },
  { name: 'Korea, Republic of', code: 'KR' },
  { name: 'Kuwait', code: 'KW' },
  { name: 'Kyrgyzstan', code: 'KG' },
  { name: "Lao People'S Democratic Republic", code: 'LA' },
  { name: 'Latvia', code: 'LV' },
  { name: 'Lebanon', code: 'LB' },
  { name: 'Lesotho', code: 'LS' },
  { name: 'Liberia', code: 'LR' },
  { name: 'Libyan Arab Jamahiriya', code: 'LY' },
  { name: 'Liechtenstein', code: 'LI' },
  { name: 'Lithuania', code: 'LT' },
  { name: 'Luxembourg', code: 'LU' },
  { name: 'Macao', code: 'MO' },
  { name: 'Macedonia, The Former Yugoslav Republic of', code: 'MK' },
  { name: 'Madagascar', code: 'MG' },
  { name: 'Malawi', code: 'MW' },
  { name: 'Malaysia', code: 'MY' },
  { name: 'Maldives', code: 'MV' },
  { name: 'Mali', code: 'ML' },
  { name: 'Malta', code: 'MT' },
  { name: 'Marshall Islands', code: 'MH' },
  { name: 'Martinique', code: 'MQ' },
  { name: 'Mauritania', code: 'MR' },
  { name: 'Mauritius', code: 'MU' },
  { name: 'Mayotte', code: 'YT' },
  { name: 'Mexico', code: 'MX' },
  { name: 'Micronesia, Federated States of', code: 'FM' },
  { name: 'Moldova, Republic of', code: 'MD' },
  { name: 'Monaco', code: 'MC' },
  { name: 'Mongolia', code: 'MN' },
  { name: 'Montserrat', code: 'MS' },
  { name: 'Morocco', code: 'MA' },
  { name: 'Mozambique', code: 'MZ' },
  { name: 'Myanmar', code: 'MM' },
  { name: 'Namibia', code: 'NA' },
  { name: 'Nauru', code: 'NR' },
  { name: 'Nepal', code: 'NP' },
  { name: 'Netherlands', code: 'NL' },
  { name: 'Netherlands Antilles', code: 'AN' },
  { name: 'New Caledonia', code: 'NC' },
  { name: 'New Zealand', code: 'NZ' },
  { name: 'Nicaragua', code: 'NI' },
  { name: 'Niger', code: 'NE' },
  { name: 'Nigeria', code: 'NG' },
  { name: 'Niue', code: 'NU' },
  { name: 'Norfolk Island', code: 'NF' },
  { name: 'Northern Mariana Islands', code: 'MP' },
  { name: 'Norway', code: 'NO' },
  { name: 'Oman', code: 'OM' },
  { name: 'Pakistan', code: 'PK' },
  { name: 'Palau', code: 'PW' },
  { name: 'Palestinian Territory, Occupied', code: 'PS' },
  { name: 'Panama', code: 'PA' },
  { name: 'Papua New Guinea', code: 'PG' },
  { name: 'Paraguay', code: 'PY' },
  { name: 'Peru', code: 'PE' },
  { name: 'Philippines', code: 'PH' },
  { name: 'Pitcairn', code: 'PN' },
  { name: 'Poland', code: 'PL' },
  { name: 'Portugal', code: 'PT' },
  { name: 'Puerto Rico', code: 'PR' },
  { name: 'Qatar', code: 'QA' },
  { name: 'Reunion', code: 'RE' },
  { name: 'Romania', code: 'RO' },
  { name: 'Russian Federation', code: 'RU' },
  { name: 'RWANDA', code: 'RW' },
  { name: 'Saint Helena', code: 'SH' },
  { name: 'Saint Kitts and Nevis', code: 'KN' },
  { name: 'Saint Lucia', code: 'LC' },
  { name: 'Saint Pierre and Miquelon', code: 'PM' },
  { name: 'Saint Vincent and the Grenadines', code: 'VC' },
  { name: 'Samoa', code: 'WS' },
  { name: 'San Marino', code: 'SM' },
  { name: 'Sao Tome and Principe', code: 'ST' },
  { name: 'Saudi Arabia', code: 'SA' },
  { name: 'Senegal', code: 'SN' },
  { name: 'Serbia and Montenegro', code: 'CS' },
  { name: 'Seychelles', code: 'SC' },
  { name: 'Sierra Leone', code: 'SL' },
  { name: 'Singapore', code: 'SG' },
  { name: 'Slovakia', code: 'SK' },
  { name: 'Slovenia', code: 'SI' },
  { name: 'Solomon Islands', code: 'SB' },
  { name: 'Somalia', code: 'SO' },
  { name: 'South Africa', code: 'ZA' },
  { name: 'South Georgia and the South Sandwich Islands', code: 'GS' },
  { name: 'Spain', code: 'ES' },
  { name: 'Sri Lanka', code: 'LK' },
  { name: 'Sudan', code: 'SD' },
  { name: 'Suriname', code: 'SR' },
  { name: 'Svalbard and Jan Mayen', code: 'SJ' },
  { name: 'Swaziland', code: 'SZ' },
  { name: 'Sweden', code: 'SE' },
  { name: 'Switzerland', code: 'CH' },
  { name: 'Syrian Arab Republic', code: 'SY' },
  { name: 'Taiwan, Province of China', code: 'TW' },
  { name: 'Tajikistan', code: 'TJ' },
  { name: 'Tanzania, United Republic of', code: 'TZ' },
  { name: 'Thailand', code: 'TH' },
  { name: 'Timor-Leste', code: 'TL' },
  { name: 'Togo', code: 'TG' },
  { name: 'Tokelau', code: 'TK' },
  { name: 'Tonga', code: 'TO' },
  { name: 'Trinidad and Tobago', code: 'TT' },
  { name: 'Tunisia', code: 'TN' },
  { name: 'Turkey', code: 'TR' },
  { name: 'Turkmenistan', code: 'TM' },
  { name: 'Turks and Caicos Islands', code: 'TC' },
  { name: 'Tuvalu', code: 'TV' },
  { name: 'Uganda', code: 'UG' },
  { name: 'Ukraine', code: 'UA' },
  { name: 'United Arab Emirates', code: 'AE' },
  { name: 'United Kingdom', code: 'GB' },
  { name: 'United States', code: 'US' },
  { name: 'United States Minor Outlying Islands', code: 'UM' },
  { name: 'Uruguay', code: 'UY' },
  { name: 'Uzbekistan', code: 'UZ' },
  { name: 'Vanuatu', code: 'VU' },
  { name: 'Venezuela', code: 'VE' },
  { name: 'Viet Nam', code: 'VN' },
  { name: 'Virgin Islands, British', code: 'VG' },
  { name: 'Virgin Islands, U.S.', code: 'VI' },
  { name: 'Wallis and Futuna', code: 'WF' },
  { name: 'Western Sahara', code: 'EH' },
  { name: 'Yemen', code: 'YE' },
  { name: 'Zambia', code: 'ZM' },
  { name: 'Zimbabwe', code: 'ZW' },
];

export const categoryIcons: {
  category: string;
  keywords: string[];
  icons: { classSelector: string }[];
}[] = [
  {
    category: 'Recent',
    keywords: ['special', 'new', 'member'],
    icons: [
      { classSelector: 'new-balloon-1' },
      { classSelector: 'new-balloon-2' },
      { classSelector: 'new-balloon-3' },
      { classSelector: 'new-balloon-4' },
    ],
  },
  {
    category: 'Advertisement',
    keywords: ['advertising', 'marketing'],
    icons: [
      { classSelector: 'advert-billboard' },
      { classSelector: 'advert-computer' },
      { classSelector: 'advert-ad' },
      { classSelector: 'advert-email' },
      { classSelector: 'advert-newspaper' },
      { classSelector: 'advert-smartphone' },
    ],
  },
  {
    category: 'Apparel',
    keywords: ['apparel', 'clothing', 'tuxedo', 'accessories', 'handbags'],
    icons: [
      { classSelector: 'apparel-pants' },
      { classSelector: 'apparel-shirt-2' },
      { classSelector: 'apparel-skirt' },
      { classSelector: 'apparel-sneaker' },
      { classSelector: 'apparel-tshirt-1' },
      { classSelector: 'apparel-tshirt-2' },
      { classSelector: 'apparel-baby-clothes' },
    ],
  },
  {
    category: 'Appliances',
    keywords: ['appliances', 'electronics'],
    icons: [
      { classSelector: 'appliances-dishwasher' },
      { classSelector: 'appliances-fridge' },
      { classSelector: 'appliances-microwave-oven' },
      { classSelector: 'appliances-toaster' },
      { classSelector: 'appliances-washing-machine' },
    ],
  },
  {
    category: 'Art',
    keywords: ['art'],
    icons: [
      { classSelector: 'art-easel' },
      { classSelector: 'art-exhibition' },
      { classSelector: 'art-paint-brush' },
      { classSelector: 'art-painting' },
      { classSelector: 'art-sketchbook' },
    ],
  },
  {
    category: 'Automotive',
    keywords: [
      'auto',
      'automobile',
      'automotive',
      'limousine',
      'transportation',
      'truck',
      'mobile',
    ],
    icons: [
      { classSelector: 'automobile-car-1' },
      { classSelector: 'automobile-car-2' },
      { classSelector: 'automobile-car-3' },
      { classSelector: 'automobile-garage' },
      { classSelector: 'automobile-van' },
    ],
  },
  {
    category: 'Barter',
    keywords: ['barter'],
    icons: [
      { classSelector: 'barter-dollar' },
      { classSelector: 'barter-employee' },
      { classSelector: 'barter-structure' },
      { classSelector: 'business-coin' },
    ],
  },
  {
    category: 'Beauty & Spa',
    keywords: ['beauty', 'spa', 'hair', 'salon', 'skin', 'tanning'],
    icons: [
      { classSelector: 'beauty-facemask' },
      { classSelector: 'beauty-hairdresser' },
      { classSelector: 'beauty-hairdryer' },
      { classSelector: 'beauty-hot-stones' },
    ],
  },
  {
    category: 'Boats and Rvs',
    keywords: ['boat', 'marine'],
    icons: [
      { classSelector: 'boats-boat' },
      { classSelector: 'boats-boat-2' },
      { classSelector: 'boats-caravan' },
      { classSelector: 'boats-caravan-2' },
      { classSelector: 'boats-sailboat' },
      { classSelector: 'boats-ship' },
    ],
  },
  {
    category: 'Building/Renovations',
    keywords: [
      'building',
      'construction',
      'home services',
      'renovation',
      'concrete',
      'contracting',
      'contractor',
      'countertops',
      'flooring',
      'hardware',
      'maintenance',
      'power washing',
      'water',
    ],
    icons: [
      { classSelector: 'building-house' },
      { classSelector: 'building-paint-bucket' },
      { classSelector: 'building-paint-roller' },
      { classSelector: 'building-tools' },
    ],
  },
  {
    category: 'Business',
    keywords: [
      'business',
      'copier',
      'office',
      'professional',
      'signs',
      'staff',
      'telemarketing',
      'telephone',
      'accounting',
      'locksmith',
    ],
    icons: [
      { classSelector: 'business-coin' },
      { classSelector: 'business-communication' },
      { classSelector: 'business-documents' },
      { classSelector: 'business-ink' },
      { classSelector: 'business-paperclip' },
    ],
  },
  {
    category: 'Cleaning',
    keywords: ['cleaning', 'housekeeping', 'janitorial'],
    icons: [
      { classSelector: 'apparel-shirt-1' },
      { classSelector: 'cleaning-broom' },
      { classSelector: 'cleaning-laundry' },
      { classSelector: 'cleaning-mop' },
      { classSelector: 'cleaning-mop-2' },
      { classSelector: 'cleaning-vacuum' },
    ],
  },
  {
    category: 'Education',
    keywords: ['education', 'instruction', 'school'],
    icons: [
      { classSelector: 'education-books-2' },
      { classSelector: 'education-books' },
      { classSelector: 'education-briefcase' },
      { classSelector: 'education-diploma' },
      { classSelector: 'education-mortarboard' },
      { classSelector: 'education-student' },
    ],
  },
  {
    category: 'Electronics',
    keywords: ['computer', 'information'],
    icons: [
      { classSelector: 'electronics-camera' },
      { classSelector: 'electronics-computer' },
      { classSelector: 'electronics-gamepad' },
      { classSelector: 'electronics-radio' },
      { classSelector: 'electronics-television' },
    ],
  },
  {
    category: 'Entertainment',
    keywords: ['entertainment', 'entertain', 'music', 'theatre', 'tickets'],
    icons: [
      { classSelector: 'entertainment-cinema' },
      { classSelector: 'entertainment-film' },
      { classSelector: 'entertainment-popcorn' },
      { classSelector: 'entertainment-ticket' },
      { classSelector: 'entertainment-ticket-2' },
      { classSelector: 'entertainment-theatre' },
      { classSelector: 'entertainment-trumpet' },
    ],
  },
  {
    category: 'Parties & Events',

    keywords: ['events', 'party', 'wedding'],
    icons: [
      { classSelector: 'events-event' },
      { classSelector: 'events-newlyweds' },
      { classSelector: 'events-party-balloons' },
      { classSelector: 'events-party-hat' },
      { classSelector: 'events-ring' },
      { classSelector: 'events-glasses' },
    ],
  },
  {
    category: 'Food & Drink',
    keywords: ['food', 'pizza', 'wine', 'bakery', 'baked'],
    icons: [
      { classSelector: 'food-bbq' },
      { classSelector: 'food-beer' },
      { classSelector: 'food-cocktail' },
      { classSelector: 'food-hot-food' },
      { classSelector: 'food-pizza' },
    ],
  },
  {
    category: 'Gifts & Certificates',
    keywords: ['gifts'],
    icons: [
      { classSelector: 'gift-certs-1' },
      { classSelector: 'gift-certs-2' },
      { classSelector: 'gifts-gift-1' },
      { classSelector: 'gifts-gift-2' },
      { classSelector: 'gifts-gift-3' },
      { classSelector: 'gifts-gift-4' },
    ],
  },
  {
    category: 'Legal',
    keywords: ['attorney', 'legal', 'security'],
    icons: [
      { classSelector: 'legal-balance' },
      { classSelector: 'legal-contract' },
      { classSelector: 'legal-law-book' },
      { classSelector: 'legal-legal-pin' },
      { classSelector: 'legal-policeman' },
    ],
  },
  {
    category: 'Fitness & Wellness',
    keywords: ['health', 'fitness', 'wellness'],
    icons: [
      { classSelector: 'health-bicycle' },
      { classSelector: 'health-dumbbell' },
      { classSelector: 'health-health' },
      { classSelector: 'health-heart' },
      { classSelector: 'health-hand-grip' },
      { classSelector: 'health-kettle-ball' },
    ],
  },
  {
    category: 'Home',
    keywords: ['home', 'housewares', 'kitchen', 'furniture', 'upholstery'],
    icons: [
      { classSelector: 'home-armchair' },
      { classSelector: 'home-chandelier' },
      { classSelector: 'home-picture' },
      { classSelector: 'home-television' },
      { classSelector: 'home-vase' },
    ],
  },
  {
    category: 'Kids',
    keywords: ['kids', 'toys', 'family', 'day care', 'childcare', 'children', 'baby'],
    icons: [
      { classSelector: 'kids-baby' },
      { classSelector: 'kids-bottle' },
      { classSelector: 'kids-bottle-2' },
      { classSelector: 'kids-robot' },
      { classSelector: 'kids-stroller' },
      { classSelector: 'apparel-baby-clothes' },
    ],
  },
  {
    category: 'Landscaping',
    keywords: ['landscaping', 'lawn', 'landscape', 'tree'],
    icons: [
      { classSelector: 'landscaping-lawn-mower' },
      { classSelector: 'landscaping-leaf' },
      { classSelector: 'landscaping-rake' },
      { classSelector: 'landscaping-trowel' },
      { classSelector: 'landscaping-wheelbarrow' },
      { classSelector: 'building-tools' },
    ],
  },
  {
    category: 'Medical & Dental',
    keywords: ['medical', 'dental', 'vision', 'chiropractor', 'eyeglasses', 'sunglasses'],
    icons: [
      { classSelector: 'medical-dental' },
      { classSelector: 'medical-eye-glasses' },
      { classSelector: 'medical-first-aid' },
      { classSelector: 'medical-heart' },
      { classSelector: 'medical-medicine' },
    ],
  },
  {
    category: 'Personal Services',
    keywords: [
      'personal',
      'dance',
      'counseling',
      'life coach',
      'martial arts',
      'massage',
      'hobbies',
      'service',
      'sewing',
      'consultant',
    ],
    icons: [
      { classSelector: 'personal-building' },
      { classSelector: 'personal-business-card' },
      { classSelector: 'personal-business-person' },
      { classSelector: 'personal-law' },
      { classSelector: 'personal-talking-people' },
    ],
  },
  {
    category: 'Pets',
    keywords: ['animal', 'pets', 'pest', 'veterinarian'],
    icons: [{ classSelector: 'pets-bone' }, { classSelector: 'pets-animal' }],
  },
  {
    category: 'Real Estate',
    keywords: ['Real Estate'],
    icons: [
      { classSelector: 'estate-chat' },
      { classSelector: 'estate-home-award' },
      { classSelector: 'estate-home' },
      { classSelector: 'estate-real-estate' },
      { classSelector: 'estate-sold' },
    ],
  },
  {
    category: 'Restaurants',
    keywords: ['dining', 'restaurants'],
    icons: [
      { classSelector: 'restaurants-cloche' },
      { classSelector: 'restaurants-food' },
      { classSelector: 'restaurants-menu' },
      { classSelector: 'restaurants-plate' },
      { classSelector: 'restaurants-restaurant' },
    ],
  },
  {
    category: 'Retail',
    keywords: [
      'consumer',
      'general',
      'flags',
      'glass',
      'retail',
      'window treatments',
      'coffee',
      'appliances',
      'rentals',
    ],
    icons: [
      { classSelector: 'retail-label-1' },
      { classSelector: 'retail-label-2' },
      { classSelector: 'retail-retail-sale' },
      { classSelector: 'retail-retail-sold' },
      { classSelector: 'retail-shop' },
    ],
  },
  {
    category: 'Sports & Recreation',
    keywords: ['sport', 'golf', 'outdoors', 'arcade', 'hunting'],
    icons: [
      { classSelector: 'sports-baseball' },
      { classSelector: 'sports-basketball' },
      { classSelector: 'sports-football' },
      { classSelector: 'sports-hockey' },
      { classSelector: 'sports-soccer' },
    ],
  },
  {
    category: 'Travel',
    keywords: ['travel', 'hospitality', 'luggage', 'accommodations'],
    icons: [
      { classSelector: 'travel-airplane' },
      { classSelector: 'travel-bunk-bed' },
      { classSelector: 'travel-location' },
      { classSelector: 'travel-sun-bed' },
      { classSelector: 'travel-plane-tickets' },
    ],
  },

  {
    category: 'Wanted',
    keywords: [],
    icons: [{ classSelector: 'wanted-loupe' }],
  },
];

export const categoryImages: { title: string; imageRef: string; subcategories: string[] }[] = [
  {
    title: 'Advertising & Web Services',
    imageRef: '/drilldownImages/advertising.jpg',
    subcategories: [],
  },
  {
    title: 'Apparel',
    imageRef: '/drilldownImages/apparel.jpg',
    subcategories: [],
  },
  {
    title: 'Automobile & Trucks',
    imageRef: '/drilldownImages/automotive.jpg',
    subcategories: [],
  },
  {
    title: 'Beauty Services & Supplies',
    imageRef: '/drilldownImages/beauty.jpg',
    subcategories: [],
  },
  {
    title: 'Boats & RV',
    imageRef: '/drilldownImages/boats.jpg',
    subcategories: [],
  },
  {
    title: 'Building & Remodeling',
    imageRef: '/drilldownImages/building.jpg',
    subcategories: [],
  },
  {
    title: 'Business Products & Services',
    imageRef: '/drilldownImages/business.jpg',
    subcategories: [],
  },
  {
    title: 'Cleaning',
    imageRef: '/drilldownImages/cleaning.jpg',
    subcategories: [],
  },
  {
    title: 'Education & Classes',
    imageRef: '/drilldownImages/education.jpg',
    subcategories: [],
  },
  {
    title: 'Entertainment',
    imageRef: '/drilldownImages/entertainment.jpg',
    subcategories: [],
  },
  {
    title: 'Events, Parties & Weddings',
    imageRef: '/drilldownImages/events.jpg',
    subcategories: [],
  },
  {
    title: 'Food & Beverage',
    imageRef: '/drilldownImages/food.jpg',
    subcategories: [],
  },
  {
    title: 'Gift Certificates',
    imageRef: '/drilldownImages/gift-certs.jpg',
    subcategories: [],
  },
  {
    title: 'Gifts & Retail',
    imageRef: '/drilldownImages/retail.jpg',
    subcategories: [],
  },
  {
    title: 'Health & Fitness',
    imageRef: '/drilldownImages/health.jpg',
    subcategories: [],
  },
  {
    title: 'Home Services & Decor',
    imageRef: '/drilldownImages/home.jpg',
    subcategories: [],
  },
  {
    title: 'Kids',
    imageRef: '/drilldownImages/kids.jpg',
    subcategories: [],
  },
  {
    title: 'Landscaping & Maintenance',
    imageRef: '/drilldownImages/landscaping.jpg',
    subcategories: [],
  },
  {
    title: 'Medical, Dental & Vision',
    imageRef: '/drilldownImages/medical.jpg',
    subcategories: [],
  },
  {
    title: 'Personal Products & Services',
    imageRef: '/drilldownImages/personal.jpg',
    subcategories: [],
  },
  {
    title: 'Pets',
    imageRef: '/drilldownImages/pets.jpg',
    subcategories: [],
  },
  {
    title: 'Real Estate',
    imageRef: '/drilldownImages/real-estate.jpg',
    subcategories: [],
  },
  {
    title: 'Travel & Accommodations',
    imageRef: '/drilldownImages/travel.jpg',
    subcategories: [],
  },
  {
    title: 'Travel By State',
    imageRef: '/drilldownImages/travel.jpg',
    subcategories: [],
  },
  {
    title: 'Wanted',
    imageRef: '/drilldownImages/wanted.jpg',
    subcategories: [],
  },
];

export const colors = [
  'Aqua',
  'Aquamarine',
  'Bisque',
  'Black',
  'BlanchedAlmond',
  'Blue',
  'BlueViolet',
  'Brown',
  'BurlyWood',
  'CadetBlue',
  'Chartreuse',
  'Chocolate',
  'Coral',
  'CornflowerBlue',
  'Cornsilk',
  'Crimson',
  'Cyan',
  'DarkBlue',
  'DarkCyan',
  'DarkGoldenRod',
  'DarkGrey',
  'DarkGreen',
  'DarkKhaki',
  'DarkMagenta',
  'DarkOliveGreen',
  'Darkorange',
  'DarkOrchid',
  'DarkRed',
  'DarkSalmon',
  'DarkSeaGreen',
  'DarkSlateBlue',
  'DarkSlateGrey',
  'DarkTurquoise',
  'DarkViolet',
  'DeepPink',
  'DeepSkyBlue',
  'DimGray',
  'DodgerBlue',
  'FireBrick',
  'ForestGreen',
  'Fuchsia',
  'Gainsboro',
  'Gold',
  'GoldenRod',
  'Grey',
  'Green',
  'GreenYellow',
  'HoneyDew',
  'HotPink',
  'IndianRed',
  'Indigo',
  'Ivory',
  'Khaki',
  'Lavender',
  'LavenderBlush',
  'LawnGreen',
  'LemonChiffon',
  'LightBlue',
  'LightCoral',
  'LightCyan',
  'LightGoldenRodYellow',
  'LightGrey',
  'LightGreen',
  'LightPink',
  'LightSalmon',
  'LightSeaGreen',
  'LightSkyBlue',
  'LightSlateGrey',
  'LightSteelBlue',
  'LightYellow',
  'Lime',
  'LimeGreen',
  'Linen',
  'Magenta',
  'Maroon',
  'MediumAquaMarine',
  'MediumBlue',
  'MediumOrchid',
  'MediumPurple',
  'MediumSeaGreen',
  'MediumSlateBlue',
  'MediumSpringGreen',
  'MediumTurquoise',
  'MediumVioletRed',
  'MidnightBlue',
  'MintCream',
  'MistyRose',
  'Moccasin',
  'Navy',
  'OldLace',
  'Olive',
  'OliveDrab',
  'Orange',
  'OrangeRed',
  'Orchid',
  'PaleGoldenRod',
  'PaleGreen',
  'PaleTurquoise',
  'PaleVioletRed',
  'PapayaWhip',
  'PeachPuff',
  'Peru',
  'Pink',
  'Plum',
  'PowderBlue',
  'Purple',
  'Red',
  'RosyBrown',
  'RoyalBlue',
  'SaddleBrown',
  'Salmon',
  'SandyBrown',
  'SeaGreen',
  'SeaShell',
  'Sienna',
  'Silver',
  'SkyBlue',
  'SlateBlue',
  'SlateGrey',
  'Snow',
  'SpringGreen',
  'SteelBlue',
  'Tan',
  'Teal',
  'Thistle',
  'Tomato',
  'Turquoise',
  'Violet',
  'Wheat',
  'Yellow',
  'YellowGreen',
];
